### ISSUE TITLE
Bug: missmatch between the estimation and the real price

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/ui-scaffold#317]
When creating a process, sometimes there's a mismatch between the estimation and the real token cost:

![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/b5e093c9-8930-4152-8edd-c61878e7c04b)

**Comment by elboletaire** [comment]
This is probably a backend error more than a frontend one, since we're passing the same UnpublishedElection object to the cost preview we're passing later to the create election.

Still, we should check our side first to ensure we're actually passing the exact same object (since a slight change like a 1 day off date could change this result).

**Comment by nigeon** [comment]
From the FE, in the tests I've checked both sources (unpublished and election (from params) and are the same. BUT I couldn't reproduce the estimation error.

Note that, there's no way to check if the price paid for an election was exactly the estimated price. So it's impossible to know if the error is an edge case, or it's a generalized estimation error. And probably that's what first should be checked.

**Comment by nigeon** [comment]
Looking at token balances before and after, 2 days, anon+secret, 2 addresses cost estimation is about 23 voctokens, but actual cost is 101 voctokens

**Comment by elboletaire** [comment]
@p4u is it possible that we have the same issue we had, were you ended up doing some kind of reset to have the proper estimations? I don't recall having estimations this way off, other than when that happened.

**Comment by jpaulet** [comment]
Solved in the backend. Closing this issue.
