### ISSUE TITLE
Display the Attributes of Each Voting Process

### ISSUE THREAD

**Issue by ferranrego** [vocdoni/ui-scaffold#461]
The voting page of a voting process should include a section that provides detailed information about the nature of each voting process. This would encompass whether the results are encrypted until the end or not, whether the voting is anonymous, the type of voting system used (simple, quadratic, etc., depending on what we support), and if it allows for vote overwriting. This enhancement will ensure greater transparency and user understanding of each voting process.

I believe it has to be in this section:
![image](https://github.com/vocdoni/ui-scaffold/assets/3515290/03a58193-209f-4cea-aec4-93cd00ed6a70)

It could be something like this:

**Vote attributes:**
Anonymous: Yes
Results encrypted until the end: No
Vote overwrite: Yes
Type: Simple choice

**Comment by elboletaire** [comment]
I would not add `simple choice` for now, since the UI does not allow to create other types. Other than that, maybe we could show it like in the create process confirm step, where you see checks of the general election options:

![imatge](https://github.com/vocdoni/ui-scaffold/assets/153305/99c62f4e-1138-4cd7-8ba3-46d57c68b3d0)

Note this change will require to remove some of the current lines, otherwise we would be repeating data.

**Comment by ferranrego** [comment]
+1. To make it more clear, I would add “Results” to the sentence “Secret until the end” otherwise it's a bit confusing what is referring to.

✅  Vote overwrite
❌  Results secret until the end
✅  Anonymous voting

Also, if we choose to use Checks and "Xs" (I'm not sure about this), I would colorize them with green and red to avoid confusion.

**Comment by elboletaire** [comment]
Just to be clear: my suggestion is not to use that as it is rn, but think if it makes sense to show it the same way and, if so, ensure we use the same component to reduce code boilerplate.
