### ISSUE TITLE
Improve token logo images loading per network

### ISSUE THREAD

**Issue by elboletaire** [vocdoni/ui-scaffold#583]
We're using trustwallet/assets to load logos of the tokens, but we have it hardcoded to only retrieve token from the ethereum network. We should update it to properly switch the network from the URL too, allowing us to load dozens of new tokens we currently aren't loading a logo for.

**Comment by selankon** [comment]
After a little research i found that provably we cannot use the chain names that come from census 3:

```json
[
  {
    "chainID": 1,
    "shortName": "eth",
    "name": "Ethereum Mainnet"
  },
  {
    "chainID": 42170,
    "shortName": "arb-nova",
    "name": "Arbitrum Nova"
  },
  {
    "chainID": 42161,
    "shortName": "arb1",
    "name": "Arbitrum One"
  },
  {
    "chainID": 8453,
    "shortName": "base",
    "name": "Base"
  },
  {
    "chainID": 100,
    "shortName": "gno",
    "name": "Gnosis"
  },
  {
    "chainID": 10,
    "shortName": "oeth",
    "name": "OP Mainnet"
  },
  {
    "chainID": 424,
    "shortName": "PGN",
    "name": "PGN (Public Goods Network)"
  },
  {
    "chainID": 11155111,
    "shortName": "sep",
    "name": "Sepolia"
  },
  {
    "chainID": 7777777,
    "shortName": "zora",
    "name": "Zora"
  }
]
```

The names are not the same of the ones on https://github.com/trustwallet/assets/tree/master/blockchains/ .

So a solution could be to get the chain names using the ethers library and see if they are the same:

```ts
async function getNetworkName(chainId) {
    const network = await ethers.providers.getNetwork(chainId);
    return network.name;
}
```

I don't really like this method because it adds another async call, but for the moment is the best solution i found. 

Any thoughts @elboletaire ??

**Comment by elboletaire** [comment]
Go async 🚀
