### ISSUE TITLE
End date improvement

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/ui-scaffold#593]
In both themes, Vocdoniapp & Onvote, the end date selection is a bit "tricky", having to select the time. To make it easier for the organizer, by default introduce the current time after selecting the date. 

Ex: Now is the 12:00 and the user selects the process to end in 3 days. Automatically add the "12:00" to the end date.

**Comment by selankon** [comment]
After a little of research I found that this behavior is not possible with this input component: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local

The problem here is that:

- We can not set a default date with only time (no date) because the format is not compatible with the input.
- We can not use a onChange callback because the onChange is only called when the date and time are selected. So we cannot await at the user date selection to set default date

Some workarounds can be

- Create a custom component with an input date connected to a input time (which not exist and we should create)
- Either, we could modify the css of this mentioned two inputs to have the look of only one component.

**Comment by selankon** [comment]
Other solution could be to set a default end date in a few hours.

As @elboletaire said, this issue is only happening to Firefox datepickers

**Comment by elboletaire** [comment]
> Other solution could be to set a default end date in a few hours.

It's actually a nice and ez hack.

**Comment by selankon** [comment]
After talk with @jpaulet we decided to close this because this error affects only to Firefox apparently and to set a default en date is not a good solution
